# Dependencies
markdown:         kramdown
highlighter:      rouge
remote_theme:     fongandrew/hydeout

# Setup
title:            Michael Kühhirt
tagline:          Personal website
baseurl:          '/About'
